artifact_uri: file:///Users/rk1103/Documents/mlflow-with-dvc/runs/0/02bf6bef4bcb41fda3b18e41be0a1cdf/artifacts
end_time: 1687388421645
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 02bf6bef4bcb41fda3b18e41be0a1cdf
run_name: grandiose-moth-994
run_uuid: 02bf6bef4bcb41fda3b18e41be0a1cdf
source_name: ''
source_type: 4
source_version: ''
start_time: 1687388411052
status: 3
tags: []
user_id: rk1103
