aliases: []
creation_timestamp: 1687388421607
current_stage: None
description: null
last_updated_timestamp: 1687388421607
name: ElasticnetWineModel
run_id: 02bf6bef4bcb41fda3b18e41be0a1cdf
run_link: null
source: file:///Users/rk1103/Documents/mlflow-with-dvc/runs/0/02bf6bef4bcb41fda3b18e41be0a1cdf/artifacts/model
status: READY
status_message: null
user_id: null
version: 1
